name: Zara Stok Kontrol

on:
  schedule:
    - cron: "*/5 * * * *"  # Her 5 dakikada bir çalışır
  workflow_dispatch:  # Manuel çalıştırmaya da izin verir

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Gerekli paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botu çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
